version: '3.8'

services:
  deepseek-ocr:
    image: alexxyk/deepocr:latest
    container_name: deepseek-ocr
    restart: unless-stopped
    
    # GPU configuration - use first GPU only
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    
    # Port mapping
    ports:
      - "5010:5010"
    
    # Environment variables
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5010/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Optional: Mount volume for model cache (uncomment if you want persistent cache)
    # volumes:
    #   - ./cache:/root/.cache/huggingface

